"""
Shared in-memory store for pending OAuth flows.

Maps OAuth `state` parameter (generated by OAuthClientProvider) to the
asyncio.Event and code holder that the background connection coroutine is
waiting on.  The /api/mcp/oauth/callback endpoint calls complete_callback()
to unblock the waiting coroutine.
"""
from typing import Any, Dict, Optional
import asyncio

# state_key -> { "name": str, "event": Event, "code": str | None }
_pending: Dict[str, Dict[str, Any]] = {}


def register(state_key: str, name: str) -> asyncio.Event:
    event = asyncio.Event()
    _pending[state_key] = {"name": name, "event": event, "code": None}
    return event


def complete_callback(state_key: str, code: str) -> bool:
    """Called by the OAuth callback route.  Returns True if state was found."""
    entry = _pending.get(state_key)
    if not entry:
        return False
    entry["code"] = code
    entry["event"].set()
    return True


def get(state_key: str) -> Optional[Dict[str, Any]]:
    return _pending.get(state_key)


def pop(state_key: str) -> Optional[Dict[str, Any]]:
    return _pending.pop(state_key, None)
