export { GeneralTab } from './GeneralTab';
export { PersonalDetailsTab } from './PersonalDetailsTab';
export { MemoryTab } from './MemoryTab';
export { DatabaseTab } from './DatabaseTab';
export { AgentsTab } from './AgentsTab';
export { CustomToolsTab } from './CustomToolsTab';
export { DataLabTab } from './DataLabTab';
export { ModelsTab } from './ModelsTab';
export { IntegrationsTab } from './IntegrationsTab';
export { McpServersTab } from './McpServersTab';
export { ConfirmationModal } from './ConfirmationModal';
export { ToastNotification } from './ToastNotification';
export { N8nFullscreenOverlay } from './N8nFullscreenOverlay';
export { CAPABILITIES } from './types';
export type { SettingsModalProps, Tab } from './types';
