/**
 * GENERATED by scripts/gen-brand.mjs — do not edit.
 *
 * Re-run `node scripts/gen-brand.mjs` after changing any number in that file.
 * `node scripts/gen-brand.mjs --audit` checks the invariant this geometry
 * exists to satisfy: a signal only ever crosses between layers through a gap
 * that belongs to both of them.
 */

/** The mark is drawn on lucide's 24 grid, so it aligns with the icon set. */
export const BRAND_GRID = 24;

export interface MarkGeometry {
  /** Arc segments, stroked. */
  readonly rings: readonly string[];
  /** The core disc, as a path so it renders through the same code as the rings. */
  readonly core: readonly string[];
  /** Signals parked on the route's waypoints. */
  readonly beads: { readonly r: number; readonly at: readonly (readonly [number, number])[] };
  readonly stroke: number;
}

/** Three layers and a solid core. Needs ~20px to read. */
export const MARK_FULL: MarkGeometry = {
  rings: [
    "M15.137 3.245A9.3 9.3 0 0 1 21.151 13.66",
    "M18.013 19.094A9.3 9.3 0 1 1 8.863 3.245",
    "M15.33 17.466A6.4 6.4 0 0 1 8.67 17.466",
    "M5.602 12.151A6.4 6.4 0 1 1 18.398 12.151",
    "M8.5 12A3.5 3.5 0 0 1 10.25 8.969",
    "M13.75 8.969A3.5 3.5 0 0 1 10.25 15.031",
  ],
  core: [
    "M12 10.7a1.3 1.3 0 1 0 0 2.6a1.3 1.3 0 1 0 0 -2.6",
  ],
  beads: { r: 1.23, at: [[12, 2.7], [17.543, 15.2], [8.969, 13.75]] },
  stroke: 1.4,
};

/**
 * The same mark with one layer removed. Below about 20px the full mark's three
 * layers merge into a disc; two layers at this weight still read. Used by the
 * favicon and the inline chat loader.
 */
export const MARK_COMPACT: MarkGeometry = {
  rings: [
    "M15.134 3.457A9.1 9.1 0 0 1 19.893 16.53",
    "M15.09 20.559A9.1 9.1 0 0 1 8.866 3.457",
    "M12.868 16.924A5 5 0 0 1 7.302 13.71",
    "M8.17 8.786A5 5 0 0 1 16.698 13.71",
  ],
  core: [
    "M12 10.3a1.7 1.7 0 1 0 0 3.4a1.7 1.7 0 1 0 0 -3.4",
  ],
  beads: { r: 1.51, at: [[12, 2.9], [15.214, 15.83]] },
  stroke: 1.8,
};

/** The size below which `Mark` and `BrandLoader` switch to the compact form. */
export const COMPACT_BELOW = 20;

/**
 * Loader timing. One period for every signal, releases spread evenly across it,
 * so a signal enters every `period / signals` seconds and the flow reads as a
 * steady conveyor rather than a crowd.
 */
export const MOTION = {
  period: 4.2,
  signals: 6,
  compactPeriod: 3.6,
  compactSignals: 3,
  /** Seconds per revolution of the whole assembly. */
  spin: 48,
} as const;
